name: Zoeice
title: Zoeice | A blog for Zoeice's Life
description: 记录时光
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: zoeice211@gmail.com
disqus_username: zoeice-com
